server:
  port: 8239

spring:
  datasource:
    name: user
    url: jdbc:mysql://39.96.86.4:3308/db2019?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    #    url: jdbc:p6spy:mysql://localhost:3306/songs?characterEncoding=utf-8&useSSL=false
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    driver-class-name: com.mysql.cj.jdbc.Driver



